// <auto-generated />
using System;
using CnabProcessor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CnabProcessor.Infrastructure.Migrations
{
    [DbContext(typeof(CnabDbContext))]
    [Migration("20251128042758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CnabProcessor.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Transaction amount in decimal format");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("Card number used in transaction");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasComment("Beneficiary's CPF (only digits)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Timestamp when record was created in database");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasComment("Date when the transaction occurred");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the store where transaction occurred");

                    b.Property<string>("StoreOwner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the store owner/representative");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time")
                        .HasComment("Time when the transaction occurred (UTC-3)");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("Transaction type: 1=Debit, 2=Boleto, 3=Financing, 4=Credit, 5=LoanReceipt, 6=Sales, 7=TedReceipt, 8=DocReceipt, 9=Rent");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Transactions_Date");

                    b.HasIndex("StoreName")
                        .HasDatabaseName("IX_Transactions_StoreName");

                    b.HasIndex("StoreName", "Date")
                        .HasDatabaseName("IX_Transactions_StoreName_Date");

                    b.ToTable("Transactions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
